src/theme.ts
- Restore focus state, disabled after setting `disableFocusRipple` to `false`
- Add custom so-called accessibility ring to the `<Button />` default and danger variant
- Add relative parameter in the `theme` object to set the width of the accessibility ring
=> [MUI-46] Restore focus state to the Button component

src/components/Tag/Tag.stories.tsx, src/components/Tag/Tag.tsx, src/components/Tag/index.ts, src/components/TagGroup/TagGroup.stories.tsx, src/components/TagGroup/TagGroup.tsx, src/components/TagGroup/index.ts, src/components/index.ts
- Add the new `Tag` component with two different variants: `default` and `light`
- Add the new `TagGroup` component with `visibleItems` prop to limit the number of visible items
- Add story to both components
=> [MUI-48] Tag and TagGroup components

src/stories/Menu.stories.tsx, src/stories/Select.stories.tsx, src/theme/theme.ts
- Add theme overrides to the `MenuItem` component, fix style when there are both icon and text
- Add correct shadow to the `Popover` component 
- Add `Menu` story to the Storybook
- Fix ubiquitous backdrop in Select or Menu components when state is set to `open`
=> [MUI-29] Menu Item

src/stories/Snackbar.stories.tsx, src/theme/theme.ts
- Add theme overrides to the `Snackbar` and `SnackbarContent` components
- Add relative stories to the Storybook
=> [MUI-62] Styled `Snackbar`

src/components/Hero/Hero.stories.tsx, src/components/Hero/Hero.tsx
There is now a required `type` prop, needed to produce a Typescript discriminated union. Set it to `text` if the hero has no image and to `image` if there is.
| Desktop  | Mobile |
| ------------- | ------------- |
| ![Screenshot 2022-08-17 at 15 21 15](https://user-images.githubusercontent.com/6032099/185144905-3dbee637-f039-4752-b9f0-11f3415145b8.png) | <img width="628" alt="Screenshot 2022-08-17 at 15 21 44" src="https://user-images.githubusercontent.com/6032099/185144998-f7b0430c-c74f-44c4-9317-aee1f3e5bb67.png"> |
| Desktop  | Mobile |
| ------------- | ------------- |
| <img width="1771" alt="Screenshot 2022-08-17 at 15 21 24" src="https://user-images.githubusercontent.com/6032099/185145142-de1766d2-5573-46ad-bef8-003149c686b0.png"> | <img width="628" alt="Screenshot 2022-08-17 at …
=> MUI 144 – Split <Hero> component into text and text+image variants

src/stories/ColorPalette.stories.mdx, src/theme/theme.ts
This PR adds the new `Colors` page, in which all the color swatches (from theme file) are present, to Storybook.
- Add new MDX file with all the color swatches
=> [MUI-164] Add color palette to Storybook

.storybook/preview.tsx, src/assets/FundedByNextGenerationEU/FundedByNextGenerationEU.stories.tsx, src/assets/LogoIOApp/LogoIOApp.stories.tsx, src/assets/LogoPagoPACompany/LogoPagoPACompany.stories.tsx, src/assets/LogoPagoPAProduct/LogoPagoPAProduct.stories.tsx, src/assets/MonogramPagoPACompany/MonogramPagoPACompany.stories.tsx, src/components/Footer/Footer.stories.tsx, src/components/HeaderAccount/HeaderAccount.stories.tsx, src/components/HeaderProduct/HeaderProduct.stories.tsx, src/components/Hero/Hero.stories.tsx, src/components/HorizontalNav/HorizontalNav.stories.tsx, src/components/Infoblock/Infoblock.stories.tsx, src/components/PartyAccountItem/PartyAccountItem.stories.tsx, src/components/PartyAccountItemButton/PartyAccountItemButton.stories.tsx, src/components/Showcase/Showcase.stories.tsx, src/components/TimelineNotification/Timeline.stories.tsx, src/components/Walkthrough/Walkthrough.stories.tsx, src/stories/Alert.stories.tsx, src/stories/Badge.stories.tsx, src/stories/Select.stories.tsx, src/stories/TextField.stories.tsx, src/theme/theme.ts
This PR adds Chromatic parameters to generate different snapshots per component, based on the resolution values set in the array `breakpointsChromaticValues`. For more information: https://www.chromatic.com/docs/viewports
⚠️ Viewport checks are not enabled by default
- Add the array `breakpointsChromaticValues`, imported by some complex components
- Add a local const `componentMaxWidth` to set a resolution upper limit of the viewport checks (eg: components that should be tested with a `500px` max-width)
=> [MUI-166] Add viewport values to Chromatic

package.json, src/stories/Typography.stories.tsx, src/theme/theme.ts, yarn.lock
This PR adds the new `monospaced` typographic variant through the `<Typography>` component. This typographic variant is especially helpful when you have a long sequence of mixed letters and numbers (e.g: IBAN code): the user can clearly see the differences between the glyph `O` (uppercase letter o) and `0` (zero number).
- Add the new `monospaced` typographic variant through the theme configuration file (`theme.ts`)
- Add relative story to Storybook
ID Pay
Run `$ yarn storybook` to launch a local instance of Storybook
=> [MUI-172] Add the new `monospaced` typographic variant

src/components/PartyAccountItemButton/PartyAccountItemButton.tsx
In the PartyAccountItemButton component, the property tabIndex is setted to zero in order to make it accessible to the focus also from keyboard commands.
Area Riservata
After updating the dependencies on the selfcare repositories, the drawer menu and the party selection of dashboard and the party selection of onboarding flows will be accessible also by pressing the TAB key on the keyboard.
=> SELC-1721 Add the property `tabIndex` to PartyAccountItemButton

src/components/PartySwitch/PartySwitch.tsx
For obtain this result, the closeIcon of mui icons-material has been wrapped into IconButton component of mui material. It has also been added an aria-label for give more accurate description of the purpose of the button.
Area Riservata
Now, opening the customDrawerMenu and type at least one character, is possible focus the closeIcon by pressing TAB key and pressing ENTER or SPACE, you are able to remove the string typed in the search.
=> SELC-1721 Make the closeIcon of customDrawerMenu focusable and clickable also with keyboard commands

src/components/LangSwitch/LangSwitch.tsx
export language related types to allow referring to them and not being forced to change the client code whenever supported languages are extended
export LangCode, LangLabels and Languages outside the LangSwitch component.
=> chore: export language types outside LangSwitch

src/components/HeaderProduct/HeaderProduct.stories.tsx, src/components/HeaderProduct/HeaderProduct.tsx
Edit the HeaderProduct component to accept a textual chip and make the bottom border configurable in size and color
- Adds the ability to render a Chip between the Product switch and the Party switch inside the HeaderProduct. The chip is configurable in textual content, color and size.
- Adds the ability to change the color and size of the default bottom border of the HeaderProduct.
Selfcare Back-office pagoPA
Some stories have been added in the Components/HeaderProduct section that can be tested with Storybook or Chromatic:
- Default Without Parties With Chip
- With Product Selection With Chip
- Without Product Selection With Chip
- With Party Selection With Chip
- With Product Selection With Party Selection With Chip
=> PASELC-54 HeaderProduct: adds Chip component and makes the bottom border configurable

src/components/ProductSwitch/ProductSwitch.tsx
This PR contains a fix to a problem where the `HeaderProduct` component was not calling the updated reference of the passed `onSelectedProduct` callback function.
The reason of the bug is due to a missing dependency in the handleClose's useCallback dependency array (`onExit`).
The fix removed completely `useCallback` since it is not really needed in this context.
PDND Interoperabilità
=> Fix: HeaderProduct calls outdated onSelectedProduct callback reference  

src/theme/theme.ts
Change MuiListItemButton to show border only on selection, accordingly to [PN-5524](https://pagopa.atlassian.net/browse/PN-5524) due to accessibility reasons in high contrast mode.
- Removes transparent border from SideMenuItem root style
- Adds transparent 
The behavior should be tested in windows high contrast mode, however the presence or absence of the border can be checked with the inspection tools
[PN-5524]: https://pagopa.atlassian.net/browse/PN-5524?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: change MuiListItemButton border to be present only on selection

src/theme/theme.ts
To fix the accessibility issue highlighted from the lighthouse tool, the color of the selected SideMenuItem has been changed to primary.dark from primary.main.
New color for selected item
-  Change sidemenu items color from primary main to primary dark
Check that the icon, text and border color is  #0062C3 and not #0073E6.
=> fix: change sidemenu items color from primary main to primary dark

src/theme/theme.ts
Changes MuiBreadcrumbs style accordingly to [PN-5714](https://pagopa.atlassian.net/browse/PN-5714)
Developed:
Design:
- Changes p font-size in breadcrumbs from 18px to 16px
- Removes underline while hovering breadcrumbs links
- Changes breadcrumbs icon size from default to 20px and increases right margin from 8 to 12
Check that the new style matches the [design](https://www.figma.com/file/pNBaYInnJjgyg1BZ1VeuJq/MUI-Italia---Design-System?type=design&node-id=6572-50395&t=bGlP4sx6t8YUYi31-0)
[PN-5714]: https://pagopa.atlassian.net/browse/PN-5714?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(PN-5714): adds overrides for MuiBreadcrumbs style in theme.ts

src/components/HeaderProduct/HeaderProduct.stories.tsx, src/components/HeaderProduct/HeaderProduct.tsx, src/components/PartyAccountItem/PartyAccountItem.stories.tsx, src/components/PartyAccountItem/PartyAccountItem.tsx, src/components/PartyAccountItemButton/PartyAccountItemButton.stories.tsx, src/components/PartyAccountItemButton/PartyAccountItemButton.tsx, src/components/PartySwitch/PartySwitch.tsx
change the PartyAccountItemButton and PartyAccountItem components adding an optional label above party title.
- added in PartyAccountItemButton component (and its parent components) property: topicPartyName 
- added in PartyAccountItem component (and its parent components) property: topicPartyName
- modified PartySwitchItem type adding property: topicPartyName 
Area Riservata.
go to storyBook and on story/components-partyaccountitembutton--with-tag or story/components-partyaccountitem--with-topic.
=> SELC-2590-add-topic-label

src/utils/ts-utils.ts
To the present day, when using the footer exported from MUI-Italy, if we do not use the href or set it as undefined in the console, the warning shown this warning: 
- Change from `"javascript:void(0)"` to `"#!"` in [this file](https://github.com/pagopa/mui-italia/blob/c434224ddb20f7caf193e3fb1442f23e66628e25/src/utils/ts-utils.ts#L30)
This small bug was found by the Authentication and Identity team during the development of io-web-profiles
This solution can also be tested by running the storybook. Watching in the console when viewing the Footer no longer displays the Warning
=> [IOPID-1083] fix console warning "dangerouslySetInnerHTML"

src/components/ProductSwitch/ProductSwitch.tsx
When opening the product selection dropdown, the current product is not correctly selected (menu item not highlighted in blue).
[ref](https://pagopa.atlassian.net/browse/PN-8759?atlOrigin=eyJpIjoiZDBkMmQ4NzYzNmJjNDgzZWE0ZjdmZWUyYzBjNjE4YWUiLCJwIjoiaiJ9)
- updated the state by setting `currentProductId` instead of `selectedId`. Previously, there was an issue where `selectedId` was being reassigned to itself without any changes.
Just test it within the project or in the storybook and try to change the product.
=> fix: ProductSwitch is now correctly showing the selected product

src/components/TimelineNotification/TimelineNotification.tsx, src/components/TimelineNotification/TimelineNotificationContent.tsx, src/components/TimelineNotification/TimelineNotificationDot.tsx, src/components/TimelineNotification/TimelineNotificationItem.tsx, src/components/TimelineNotification/TimelineNotificationOppositeContent.tsx, src/components/TimelineNotification/TimelineNotificationSeparator.tsx, src/utils/ts-utils.ts
Added the ability to pass props using `...props.sx`.
[ref](https://pagopa.atlassian.net/browse/PN-7135?atlOrigin=eyJpIjoiYmE1NWJhMTc3YjRlNDRhY2EyNjk1MjM2MzU1NGU1MzgiLCJwIjoiaiJ9)
- Modified `TimelineNotification.tsx` and `TimelineNotification.tsx` to allow passing props using `...props.sx`.
There isn't a definitive way to test it as it needs to be used within the project, by adding new parameters, to ensure their correct application.
=> PN-7135-mui-italia-ds-bug-ui-mittente-pagina-dettaglio-di-una-notifica-mobile

src/components/EnvironmentBanner/EnvironmentBanner.stories.tsx, src/components/EnvironmentBanner/EnvironmentBanner.tsx
Instead of passing the environment, one should pass the color key (`info` or `warning`) to generate the appropriate color. This is an intermediate PR. The next one will give the opportunity to pass in any color in the MUI Italia palette. This is due to updated requirements in Interoperabilità after the introduction of the "Ambiente di attestazione" product.
Interoperabilità
One would pass the `env` property (`test` or `prod`) to set the ribbon background color
One would pass the `bgColor` property (`info` or `warning`) to set the ribbon background color
=> Updated EnvironmentBanner prop to pass background color to ribbon

src/theme/theme.ts
increase padding to MuiLink to make it as nearest as possible to minimum 24x target size.
-  Add 1px padding top to MuiLink
-  Add 1px padding bottom to MuiLink
Piattaforma Notifiche -> SEND
Run storybook and check Links are minimum 23,97px.
=> fix(PN-10793): increase padding to MuiLink

src/components/Tag/Tag.tsx, src/theme/theme.ts
To ensure greater accessibility, the colors of chips and tags have been modified.
- Customization of the outlined variant for the default and primary chips.
- Specific styles for the outlined default chip, including border color, avatar background color, and text color.
- Consolidation and simplification of shared styles across different color variants.
Area Riservata (Selfcare)
Describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.
npm run storybook and go to chips and tag component. Make sure colors are …
=> [SELC-4552] Feat: update styles for Tag and Chip components

src/components/PartyAccountItemButton/PartyAccountItemButton.tsx, src/components/PartySwitch/PartySwitch.tsx
Resposive design of the Drawer in the HeaderProduct Component.
- Change the stle of the drawer menu to follow new responsive mui italia design
- Add x icon button to allow closing of the drawer.
Area Riservata
In the terminal run npm run storybook and go to HeaderProduct component. Check if in diferent viewports with chrome dev tools the Drawer follows the style in the figma below.
https://www.figma.com/design/pNBaYInnJjgyg1BZ1VeuJq/MUI-Italia---Design-System?node-id=14047-93971&t=wW5w040qnxzjO93b-4
=> [SELC-4585] Feat: adapt drawer component to responsive design

package.json, yarn.lock
This PR resolves a security vulnerability in the body-parser package by enforcing version 1.20.3 in the project's dependency tree. The vulnerability could lead to a denial of service when URL encoding is enabled. The change ensures that the patched version of body-parser is used across the project, mitigating the potential risk. Its a good practice to ensure that the dependency tree remains clean and that no potentially vulnerable code exist.
https://github.com/advisories/GHSA-qwcr-r2fm-qrc7/dependabot?query=user:pagopa
- Added a resolution for body-parser to version 1.20.3 in package.json
- Area Riservata
- Run yarn why body-parser to confirm that the previous installed version is lower that 1.20.3
- Run yarn install 
- Run  yarn why body-parser to confirm the new version is 1.20.3
- …
=> [SELC-5660] Feat: Resolve body-parser vulnerability by forcing version 1.20.3

src/stories/IconButton.stories.tsx, src/theme/theme.ts
Updated IconButton style to follow mui design figma https://www.figma.com/design/pNBaYInnJjgyg1BZ1VeuJq/MUI-Italia---Design-System?node-id=10130-48783&t=mTYs3IwgSsE4iZZz-4
primary:
default:
- updated style of default color variant
- updated style of icon button primary color variant
- removed deprecated ComponentStory, ComponentMeta imports
Area Riservata Enti
yarn storybook
=> [SELC-6649] feat: update IconButton styles default and primary

src/components/HeaderAccount/HeaderAccount.stories.tsx, src/components/HeaderAccount/HeaderAccount.tsx
This change allows to translate the HeaderAccount component passing custom strings to replace the fixed ones
- Added an optional translation map object as prop to the HeaderAccount component
- Added a new storybook story to illustrate the new behaviour
Area Riservata Cittadino - Reference in issue [P4PU-945](https://pagopa.atlassian.net/browse/P4PU-945)
story example has been added to the HeaderAccount stories, you can check it running the command
```bash
yarn storybook
```
[P4PU-945]: https://pagopa.atlassian.net/browse/P4PU-945?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: [P4PU-945] allowing HeaderAccount component to be translated
