pagopa/mui-italia

colors/index.d.ts
colors/italia.d.ts
index.d.ts
theme.d.ts

Types definition, useful when used in a typescript project

Types definition

---

src/theme.ts

- Updated all the basic color values, indicator values included (error, warning, success, etc…)
- Updated all the basic typography values
- Add new typographic variants: `headline`, `sidenav` and `caption-semibold`
- Add new `blueItaly` color value
- Add support for basic responsive typography, configurable through `responsiveBreakpoint` parameter

[MUI 2] Update color and typography related values

---

src/stories/Breadcrumbs.stories.tsx
src/stories/Button.stories.tsx
src/theme.ts

- Add basic style applied to the entire parent container
- Add story about the basic variant with two items (Parent link + Current page)

[MUI-32] Custom Breadcrumbs

---

src/stories/Tooltip.stories.tsx
src/theme.ts
yarn.lock

- Add basic style applied to the `<Tooltip />`
- Add story about the two basic variants (Default & With Arrow)

[MUI-32] Custom Tooltip

---

.gitignore
src/stories/Button.stories.tsx
src/stories/Chips.stories.tsx
src/theme.ts

- Add custom style to the `<Chip />` component
- Add new `extraLight` color value to the status colours in the main palette
- Add related story about the component variants (Default & Deletable)

[MUI-28] Custom Chips

---

src/theme.ts

- Change color value of the Error state to increase contrast and improve accessibility. The change affects all the elements: label, icon color, helper text, etc…

[MUI-82] Change Textfield error state to increase contrast

---

src/stories/Backdrop.stories.tsx
src/theme.ts

- Add custom background color to the `<Backdrop />` component
- Add related story to Storybook

[MUI-63] Custom Backdrop

---

src/stories/Typography.stories.tsx
src/theme.ts

- Add `body2` typographic (responsive) style with relative story

[MUI-72] Add `body2` typographic style

---

src/stories/Select.stories.tsx
src/stories/Typography.stories.tsx

- Add `<Select />` story to enable test of two component states: `Default` and `Error`

[MUI-81] Add Select to Storybook

---

.devops/code-review-pipelines.yml

- Delete `danger` task because the relative command doesn't exist in the current repository
- Temporarily disable the `test` task

[MUI-104] Fix code review pipeline process 

---

package.json

- Update peer dependencies to fix install errors in dev environments where React version is above `17.0.0`

[MUI-105] Update peer dependencies

---

package.json
src/theme/theme.ts
tsconfig.json
yarn.lock

- Change output module type, from `exnext` to `commonjs`
- Move all MUI dependencies from main dependencies to `devDependencies` and `peerDependencies` to avoid conflicts with local packages when a custom component is used
- [Minor] Change default background color in the theme file

[MUI-111] Fix PN dev environment 

---

src/stories/IconButton.stories.tsx
src/theme/theme.ts

- Add theme overrides to the `IconButton` component
- Disable state colour variants (warning, error, etc…)
- Add relative story to Storybook

[MUI-77] `IconButton` component

---

src/stories/Stepper.stories.tsx
src/theme/theme.ts

- Add theme overrides to the `Stepper` component
- Add relative stories to Storybook

[MUI-59] `Stepper` component

---

src/stories/Card.stories.tsx
src/theme/theme.ts

* Add theme overrides to the `Card` component
* Add Storybook story with `Default` and `Media` variants

[MUI-58] `Card`

---

src/stories/Switch.stories.tsx
src/theme/theme.ts

* Add theme overrides to the `Switch` component
* Disable other variants than default and primary ones

[MUI-54] Switch

---

src/components/Footer/Footer.tsx

- Adds currentLangCode prop to Footer component

fix: add current language prop to Footer

---

src/components/Hero/Hero.tsx
src/components/HorizontalNav/HorizontalNav.tsx
src/components/Infoblock/Infoblock.tsx
src/components/Showcase/Showcase.tsx
src/components/Walkthrough/Walkthrough.tsx

- add JSX Element type to landing page components content props

fix: add jsx element type to landing components props

---

src/components/Infoblock/Infoblock.tsx

fix: add padding-top to images in infoblock

---

src/components/Walkthrough/Walkthrough.stories.tsx
src/components/Walkthrough/Walkthrough.tsx

Adds isSequential  prop to items that removes number and arrow

fix: adds sequence prop to Walkthrough items

---

src/components/LangSwitch/LangSwitch.tsx

Include a summary of the changes.
- Feature A
- Feature B
Describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

SELC-1683 - modified aria-label in footer language selection

---

src/components/TOSAgreement/TOSAgreement.tsx

Interop's `TOSAgreement` implementation design changed removing the children's content.
- Changed AgreementTOS children prop to optional
Interoperabilità

[MUI-173] Changed AgreementTOS children prop to optional

---

src/components/ButtonNaked/ButtonNaked.stories.tsx
src/theme/theme.ts

- Added color variant "error" to `ButtonNaked` component.
Interoperabilità
"color" option value has been added to the `ButtonNaked` story.

[MUI 174] Added color variant "error" to ButtonNaked component

---

src/components/SingleFileInput/SingleFileInput.tsx

This PR fixes the problem with the SingleFileInput wrongly submitting the form when clicking the dropzone area to open the system file selection window.
- Added `type="button"` attribute to the dropzone button
- Removed useless id generation computations on rerender
Interoperabilità

[MUI 175] Fix form submit on SingleFileInput click

---

src/components/CopyToClipboardButton/CopyToClipboardButton.tsx
src/stories/TextField.stories.tsx
src/theme/theme.ts

Truncated long text in select input and in select dropdown
- Added some stories to test various select cases
- Updated theme.ts files with new css rules for select input and select dropdown
Run the storybook and check that various select types are rendered correctly

long text in select input and dropdown - pn-4840

---

src/components/HeaderAccount/HeaderAccount.tsx

Updated header documentation link label from "Documentazione" to "Manuale Operativo" and icon from `Description` to `MenuBook`
Storybook

[MUI-186] Updated header's description link label and icon

---

src/theme/theme.ts

insert fix for shadow of switch
Developed
Design
-insert in theme.ts the definition of shadow of switch
view a shadow in Tos component which renders the switch

fix: insert fix for shadow of switch

---

src/components/ProductAvatar/ProductAvatar.stories.tsx
src/components/ProductAvatar/ProductAvatar.tsx

Rescaled the padding in the ProductAvatar component and added "prod-io-premium" case in stories to control how it would be displayed at various sizes
- Feature A
- Feature B
Describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

SELC-2531 Rescaled the padding in the ProductAvatar component + added "prod-io-premium" case in stories

---

package.json
src/components/PartySwitch/PartySwitch.tsx
src/components/ProductSwitch/ProductSwitch.tsx
yarn.lock

update MUI to its latest version, fix API changes

Update mui to latest version

---

publiccode.yml

This PR introduces the `publiccode.yml` file in the repo in order to be correctly rendered inside the Developers Italia catalog. 
- Add publiccode.yml to the repo's root
Thanks @dmnplb

chore: add publiccode.yml metadata file

---

src/components/PartySwitch/PartySwitch.tsx

This PR introduces improvements to the party filtering and pagination/lazy loading functionality. It refactors the code to simplify the management of visible parties and ensures robust handling of edge cases.
- Simplified state management by managing only the visible subset of parties.
- Implemented pagination/lazy loading functionality with scroll-based loading.
Area Riservata
Ensure the parties array contains large number of parties over 3k+.
Verify that filtering works correctly with different search queries.
Test scroll-based loading by …

[SELC-4696] Feat:  Implement Scroll-based Pagination/Lazy Loading

---

src/components/Tag/Tag.tsx

Added sx prop to Tag component
Piattaforma Notifiche - SEND

fix: add sx prop to Tag component

---

.github/workflows/deploy-pipelines.yml

Include a summary of the changes.
- Feature A
- Feature B
Describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

Fix npm publish CI/CD

---

src/theme/theme.ts

This PR updates the button (text) component's behavior and style to ensure better adherence to the [Figma design ](https://www.figma.com/design/pNBaYInnJjgyg1BZ1VeuJq/MUI-Italia---Design-System?node-id=6543-36744&t=16WAvRlHODrwDFDM-0) specifications and to meet accessibility standards, specifically in terms of contrast.
AS IS
TO BE
- Updated Button Text Style
- Hover State Modifications
checkout pagoPA https://checkout.pagopa.it/
`yarn storybook`

fix(button-text): update muiButton text according to contrast

---

src/components/SingleFileInput/SingleFileInput.tsx
src/components/SingleFileInput/utils.ts

Some changes to `SingleFileInput` component that fix the vertical layout and change the loading according the figma layout
- Changed layout props in `SingleFileInput` component file and in its `utils` file
Run storybook in SingleFileInput section with the vertical prop set to true

fix SingleFileInput layout

---

.github/workflows/deploy-pipelines.yml

In questa pr aggiungo la possibilità di creare da un branch `release-*` una release stabile.
In questo modo, usando lo stesso branch di release, si possono testare le pre-release e poi staccare una release stabile.
Al team di admin, non resta poi che mergiare il branch di `release-*` in `main`.

feat: create stable release from release branch

---

src/components/TOSAgreement/TOSAgreement.stories.tsx
src/theme/muiSwitch.ts

Fix shadow and spaces for switch
Fixed version
- Turn overflow to visible
- Add padding to switch in TOSAgreement component
SEND
Run `yarn storybook` and check Switch element

fix: overflow switch
